version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${PORT}"

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "${MINIO_PORT_API}:${MINIO_PORT_API}"
      - "${MINIO_PORT_CONSOLE}:${MINIO_PORT_CONSOLE}"
    env_file:
      - .env
    command: server /data --console-address ":${MINIO_PORT_CONSOLE}"
    volumes:
      - minio_data:/data
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_backend
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
    restart: always


volumes:
  postgres_data:
  minio_data: