# Generated by Django 4.2.1 on 2025-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants_app', '0015_remove_collection_image_url_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_type',
            name='image_url_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото типа растения'),
        ),
    ]
