# Generated by Django 4.2.1 on 2025-03-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants_app', '0016_plant_type_image_url_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='type_rec',
        ),
        migrations.DeleteModel(
            name='Type_Recommendation',
        ),
    ]
